services:
  recommendation-service:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP
      - FLASK_ENV
      - SQLALCHEMY_DATABASE_URI
      - EUREKA_SERVER_URL
      - APP_NAME
      - SERVER_PORT
      - INSTANCE_HOST

    depends_on:
      - db
      - eureka-server
    networks:
      - event-network

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: anas2000
      POSTGRES_DB: recommendation_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - event-network

  eureka-server:
    image: my-eureka-server  
    ports:
      - "8761:8761"
    networks:
      - event-network

  api-gateway:
    image: my-api-gateway
    ports:
      - "9000:9000"
    depends_on:
      - recommendation-service
      - eureka-server
    networks:
      - event-network

volumes:
  postgres_data:

networks:
  event-network:
    driver: bridge
